version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/blok


    steps:
      - checkout
      - run: mvn clean package
      - run: ls
      - store_artifacts:
          path: target
          destination: artifacts
      - add_ssh_keys
      - deploy:
          name: Deploy to servers
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o BatchMode=yes -o StrictHostKeyChecking=no dhillon@158.69.121.66 "uptime"
              scp ./target/test-1.0-SNAPSHOT.jar dhillon@158.69.121.66:~/master/plugin.jar
            fi

            if [ "${CIRCLE_BRANCH}" == "working" ]; then
              ssh -o BatchMode=yes -o StrictHostKeyChecking=no dhillon@158.69.121.66 "uptime"
              scp ./target/test-1.0-SNAPSHOT.jar dhillon@158.69.121.66:~/working/plugin.jar
            fi